#!/usr/bin/env python3
"""
06_visualization/publication_figures.py

Generates publication-grade figures:
  Fig 5: Expression heatmap (10-gene panel × all donors)
  Fig 9: SHAP summary (requires shap package)
  Fig 10: Gene panel summary card (table figure)

Figures 2 (volcano), 3 (Venn), 4 (feature importance), 6 (LOOCV ROC),
and 7 (individual gene AUC) are generated by their respective scripts.

Outputs (all 300 DPI PNG + SVG):
  figures/expression_heatmap.png/.svg
  figures/shap_summary.png/.svg       (if shap installed)
  figures/gene_panel_card.png/.svg
"""

import os, sys, logging, warnings, pickle
import numpy as np
import pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
warnings.filterwarnings("ignore")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import (DATA_PROCESSED, RESULTS_DIR, FIGURES_DIR, LOGS_DIR, MODELS_DIR,
                    DISCOVERY_DATASETS, PALETTE_T2D, PALETTE_CTRL, FIGURE_DPI)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s",
                    handlers=[logging.StreamHandler()])
log = logging.getLogger(__name__)

def save_fig(fig, name):
    for fmt in ["png","svg"]:
        fig.savefig(os.path.join(FIGURES_DIR, f"{name}.{fmt}"), dpi=FIGURE_DPI, bbox_inches="tight")
    plt.close(fig)
    log.info(f"  Saved: {name}.png/.svg")

def fig_expression_heatmap():
    gse_id      = DISCOVERY_DATASETS[0]
    expr_path   = os.path.join(DATA_PROCESSED, f"{gse_id}_expr_normalized.csv")
    labels_path = os.path.join(DATA_PROCESSED, f"{gse_id}_labels.csv")
    panel_path  = os.path.join(RESULTS_DIR, "final_gene_panel.csv")
    if not all(os.path.exists(p) for p in [expr_path, labels_path, panel_path]):
        log.warning("  Heatmap: missing files — skipping"); return

    expr   = pd.read_csv(expr_path, index_col=0)
    ldf    = pd.read_csv(labels_path)
    labels = dict(zip(ldf["sample_id"], ldf["label"]))
    panel  = pd.read_csv(panel_path)
    genes  = panel["gene"].tolist()

    # Use symbols if available
    sym_map = {}
    if "gene_symbol" in panel.columns:
        sym_map = dict(zip(panel["gene"], panel["gene_symbol"]))

    avail  = [g for g in genes if g in expr.index]
    if not avail: log.warning("  No panel genes in expr — skipping heatmap"); return

    common = [c for c in expr.columns if c in labels and labels[c] in [0,1]]
    sub    = expr.loc[avail, common]
    y      = np.array([labels[c] for c in common])
    order  = np.argsort(y)
    sub_s  = sub.iloc[:, order]; y_s = y[order]

    sub_z = sub_s.subtract(sub_s.mean(axis=1), axis=0).divide(sub_s.std(axis=1) + 1e-8, axis=0)

    # Row labels: symbol if available
    row_labels = [sym_map.get(g, g) for g in avail]

    fig, ax = plt.subplots(figsize=(max(9, len(common)*0.17), max(5, len(avail)*0.42)))
    sns.heatmap(sub_z, cmap="RdBu_r", center=0, vmin=-2.5, vmax=2.5,
                xticklabels=False, yticklabels=row_labels,
                linewidths=0, ax=ax,
                cbar_kws={"label": "Z-score", "shrink": 0.5})
    ax.set_yticklabels(ax.get_yticklabels(), fontsize=10, style="italic")

    # Top colour bar for sample labels
    for i, lbl in enumerate(y_s):
        ax.add_patch(plt.Rectangle((i, -0.6), 1, 0.5,
                                    color=PALETTE_T2D if lbl==1 else PALETTE_CTRL,
                                    transform=ax.transData, clip_on=False))
    from matplotlib.patches import Patch
    ax.legend(handles=[Patch(color=PALETTE_T2D, label="T2D"), Patch(color=PALETTE_CTRL, label="Non-diabetic")],
              loc="upper right", bbox_to_anchor=(1.18, 1.08), fontsize=9)
    ax.set_xlabel("Samples (sorted by diagnosis)", fontsize=11)
    ax.set_title(f"10-Gene Diagnostic Panel — Expression Heatmap\n{gse_id} (n={len(common)})", fontsize=11)
    plt.tight_layout()
    save_fig(fig, "expression_heatmap")

def fig_shap():
    try:
        import shap
    except ImportError:
        log.warning("  shap not installed — skipping SHAP figure. Install: pip install shap")
        return

    model_path = os.path.join(MODELS_DIR, "Random_Forest.pkl")
    if not os.path.exists(model_path):
        log.warning("  RF model not found — skipping SHAP"); return

    with open(model_path, "rb") as f:
        md = pickle.load(f)
    model = md["model"]; panel_genes = md["panel_genes"]

    gse_id      = DISCOVERY_DATASETS[0]
    expr_path   = os.path.join(DATA_PROCESSED, f"{gse_id}_expr_normalized.csv")
    labels_path = os.path.join(DATA_PROCESSED, f"{gse_id}_labels.csv")
    if not os.path.exists(expr_path): return

    expr   = pd.read_csv(expr_path, index_col=0)
    ldf    = pd.read_csv(labels_path)
    labels = dict(zip(ldf["sample_id"], ldf["label"]))
    common = [c for c in expr.columns if c in labels and labels[c] in [0,1]]
    avail  = [g for g in panel_genes if g in expr.index]
    X      = expr.loc[avail, common].T.fillna(0)

    X_sc       = model.named_steps["scaler"].transform(X.values)
    rf         = model.named_steps["clf"]
    explainer  = shap.TreeExplainer(rf)
    shap_vals  = explainer.shap_values(X_sc)
    sv = shap_vals[1] if isinstance(shap_vals, list) else shap_vals

    panel  = pd.read_csv(os.path.join(RESULTS_DIR, "final_gene_panel.csv"))
    sym_map = {}
    if "gene_symbol" in panel.columns:
        sym_map = dict(zip(panel["gene"], panel["gene_symbol"]))
    feat_names = [sym_map.get(g, g) for g in avail]

    shap.summary_plot(sv, X_sc, feature_names=feat_names, plot_type="dot", show=False)
    fig = plt.gcf()
    fig.suptitle("SHAP Feature Importance — Random Forest (T2D class)", fontsize=11, y=1.01)
    plt.tight_layout()
    save_fig(fig, "shap_summary")

def fig_gene_panel_card():
    panel_path = os.path.join(RESULTS_DIR, "final_gene_panel.csv")
    deg_path   = os.path.join(RESULTS_DIR, "deg_results.csv")
    if not os.path.exists(panel_path): return

    panel = pd.read_csv(panel_path)
    if os.path.exists(deg_path):
        deg   = pd.read_csv(deg_path)[["gene","log2FC","adj_pvalue"]]
        panel = panel.merge(deg, on="gene", how="left")

    sym_map = {}
    if "gene_symbol" in panel.columns:
        sym_map = dict(zip(panel["gene"], panel["gene_symbol"]))

    col_labels = ["Symbol / ID", "Votes\n(/3)", "Score", "log₂FC", "FDR p"]
    rows = []
    for _, r in panel.iterrows():
        sym  = sym_map.get(r["gene"], r["gene"])
        fc   = f"{r['log2FC']:+.2f}"  if "log2FC"    in r and not pd.isna(r.get("log2FC"))    else "N/A"
        fdr  = f"{r['adj_pvalue']:.2e}" if "adj_pvalue" in r and not pd.isna(r.get("adj_pvalue")) else "N/A"
        rows.append([sym, str(int(r["votes"])), f"{r['composite_score']:.3f}", fc, fdr])

    fig, ax = plt.subplots(figsize=(10, max(4, len(rows)*0.58 + 1.5)))
    ax.axis("off")
    tbl = ax.table(cellText=rows, colLabels=col_labels, cellLoc="center", loc="center", bbox=[0,0,1,1])
    tbl.auto_set_font_size(False); tbl.set_fontsize(10)

    for j in range(len(col_labels)):
        tbl[0,j].set_facecolor("#1F4E79"); tbl[0,j].set_text_props(color="white", fontweight="bold")

    for i in range(1, len(rows)+1):
        for j in range(len(col_labels)):
            tbl[i,j].set_facecolor("#EBF5FB" if i%2==0 else "white")
        if "log2FC" in panel.columns:
            try:
                fc = panel.iloc[i-1].get("log2FC", 0)
                if not pd.isna(fc):
                    tbl[i,3].set_facecolor("#FADBD8" if fc > 0 else "#D6EAF8")
            except Exception:
                pass

    ax.set_title("Final Diagnostic Gene Panel", fontsize=13, fontweight="bold", y=1.02, color="#1F4E79")
    plt.tight_layout()
    save_fig(fig, "gene_panel_card")

def main():
    log.info("Generating publication figures...")
    fig_expression_heatmap()
    fig_shap()
    fig_gene_panel_card()
    log.info("Done.")

if __name__ == "__main__":
    main()
